/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/build-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Build various types of links. */
        post: operations["BuildLinks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get list of id value pairs for a given entity. */
        get: operations["List"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/location-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Retrieve links to the location search pages of various providers. */
        post: operations["GetLocationLinks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nearby-places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Get nearby places for a given place name or place ID. */
        post: operations["NearbyPlaces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Search for hotels and offers by various criteria. */
        post: operations["Search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Long polling version of the /search endpoint. */
        post: operations["PollSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get suggested search results for a given query. */
        get: operations["Suggest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BedConfiguration: {
            /**
             * Format: int64
             * @description Number of beds.
             */
            count: number;
            /** @description Description of the bed. */
            description?: string;
            /** @description Name of the bed. */
            name?: string;
            /** @description Size of the bed. */
            size: string;
            /** @description Type of the bed. */
            type?: string;
        };
        Bedroom: {
            /** @description How beds are configured in the bedroom. */
            bedConfigurations?: components["schemas"]["BedConfiguration"][];
            /** @description Bedroom description. */
            description?: string;
            /** @description Name of bedroom. */
            name?: string;
        };
        BuildLinksRequest: {
            homePageLinkParams?: components["schemas"]["HomePageLinkParams"];
            searchPageLinkParams?: components["schemas"]["SearchPageLinkParams"];
        };
        BuildLinksResponse: {
            /** @description Home page link if homePageLinkParams were provided. */
            homePageLink?: string;
            /**
             * @description The list of search page links if searchPageLinkParams were provided.
             *     The order is the same as in the searchPageLinkParams.urls.
             */
            searchPageLinks?: string[];
        };
        CancellationPenalty: {
            /**
             * Format: double
             * @description Fixed amount of the penalty.
             */
            amount?: number;
            /** @description Currency of the fixed amount. */
            currency?: string;
            /** @description Date and time when the penalty stops to apply. */
            end?: string;
            /** Format: int64 */
            nights?: number;
            /** Format: double */
            percent?: number;
            /** @description Date and time when the penalty starts to apply. */
            start?: string;
        };
        ErrorResponse: {
            /** @description Error message */
            message?: string;
        };
        Filters: {
            /** @description The list of facility ids. */
            facilities?: number[];
            /**
             * @description Free cancellation filter. If true, only offers with free cancellation will be returned.
             *     If false, only offers without free cancellation will be returned.
             *     Omits the filter if not set.
             */
            freeCancellation?: boolean;
            /**
             * Format: int64
             * @description Minimum overall guest rating.
             */
            guestRating?: number;
            /**
             * @description Meal plan filters. When omitted or empty, no meal-plan filter is applied.
             *     `breakfastIncluded` is not breakfast-only: it can match breakfast, halfBoard, fullBoard, and allInclusive offers.
             *     Multiple values match offers with any requested meal plan.
             */
            mealPlans?: ("breakfastIncluded" | "lunch" | "dinner" | "halfBoard" | "fullBoard" | "allInclusive")[];
            /** @description The list of property type ids to exclude. */
            notPropertyTypes?: number[];
            price?: components["schemas"]["PriceFilter"];
            /** @description The list of property type ids. */
            propertyTypes?: number[];
            /**
             * @description The list of star ratings.
             * @example 4,5
             */
            starRatings?: number[];
            /** @description The list of theme ids. */
            themes?: number[];
        };
        GuestRating: {
            /** Format: double */
            cleanliness?: number;
            /** Format: double */
            dining?: number;
            /** Format: double */
            facilities?: number;
            /** Format: double */
            location?: number;
            /** Format: double */
            overall?: number;
            /** Format: double */
            pricing?: number;
            /** Format: double */
            rooms?: number;
            /** Format: double */
            service?: number;
        };
        HomePageLinkParams: {
            /** @description Arbitrary string for tracking and reporting. */
            label?: string;
        };
        Hotel: {
            anchorRate?: components["schemas"]["Rate"];
            details?: components["schemas"]["HotelDetails"];
            error?: string;
            /** @description Hotel ID if queried by hotel IDs. */
            id?: string;
            /** @description The list of hotel offers. */
            offers: components["schemas"]["Offer"][];
            /** @description Hotel name if queried by hotel names. */
            requestedName?: string;
            /**
             * @description Rooms configuration.
             *     Non empty when rooms optimization is applied.
             */
            roomsConfig?: string;
        };
        HotelDetails: {
            /** @description Address of the hotel. */
            address: string;
            /** @description City name. */
            cityName?: string;
            /**
             * Format: int64
             * @description Distance from city center in meters.
             */
            distanceFromCityCentre?: number;
            /** @description The list of hotel facility ids. */
            facilities?: number[];
            guestRating?: components["schemas"]["GuestRating"];
            /** @description The list of hotel images. */
            images?: string[];
            location: components["schemas"]["LatLon"];
            /** @description Name of the hotel. */
            name: string;
            /**
             * Format: int64
             * @description Review count.
             */
            reviewCount?: number;
            /**
             * Format: int64
             * @description Star rating from 0 to 5.
             */
            starRating?: number;
            /** @description URL of the hotel on Vio website. */
            vioUrl: string;
        };
        HotelID: {
            /** @description Hotel ID if queried by hotel IDs. */
            id?: string;
            /** @description Hotel name if queried by hotel names. */
            requestedName?: string;
        };
        HotelNamesQuery: {
            /**
             * @description City of hotels. Use this parameter to refine the search
             *     if there are hotels with the same names in another city.
             */
            city?: string;
            /**
             * @description Country of hotels. Use this parameter to refine the search
             *     if there are hotels with the same names in another country.
             */
            country?: string;
            /**
             * Format: double
             * @description Latitude in degrees. Use this parameter together with `lon` and optionally `radius`
             *     to filter hotels by geographic proximity.
             */
            lat?: number;
            /**
             * Format: double
             * @description Longitude in degrees. Use this parameter together with `lat` and optionally `radius`
             *     to filter hotels by geographic proximity.
             */
            lon?: number;
            /** @description The list of hotel names to query. */
            names: string[];
            /**
             * @description When set to true, disables the fallback to optional filters for name mapping.
             *     By default (false), if hard filters (country/city) fail to match, the system
             *     will retry with optional filters for backward compatibility.
             */
            noMappingFallback?: boolean;
            /**
             * Format: int64
             * @description Radius in meters for geographic filtering. If not specified, defaults to 50000 meters (50km).
             *     Only used when lat and lon are provided.
             */
            radius?: number;
        };
        LatLon: {
            /**
             * Format: double
             * @description Latitude in degrees
             */
            lat?: number;
            /**
             * Format: double
             * @description Longitude in degrees
             */
            lon?: number;
            /**
             * Format: int64
             * @description Radius of the geolocation in meters
             */
            radius?: number;
        };
        Layout: {
            /**
             * Format: double
             * @description Surface area of this room in square meters.
             */
            area?: number;
            /**
             * Format: int64
             * @description Number of bathrooms.
             */
            bathroomCount?: number;
            /**
             * Format: int64
             * @description Number of bedrooms.
             */
            bedroomCount?: number;
            /** @description Available bedroom configurations. */
            bedrooms?: components["schemas"]["Bedroom"][];
        };
        ListItem: {
            /**
             * Format: int64
             * @description List item ID.
             */
            id?: number;
            /** @description Translated list item value. */
            value?: string;
        };
        LocationLinksRequest: {
            /** @description Unique ID identifying users. */
            anonymousId?: string;
            /**
             * Format: date
             * @description Check in date (YYYY-MM-DD).
             * @example 2021-10-10
             */
            checkIn?: string;
            /**
             * Format: date
             * @description Check out date (YYYY-MM-DD).
             * @example 2021-10-11
             */
            checkOut?: string;
            /**
             * @description 3-char ISO 4217 currency code.
             * @example EUR
             */
            currency: string;
            /** @description Arbitrary string for tracking and reporting. */
            label?: string;
            /**
             * @description Language code that will be used for translation of strings for humans.
             * @example en
             * @enum {string}
             */
            language: "ar" | "bg" | "ca" | "cs" | "cz" | "da" | "de" | "en" | "en-GB" | "es" | "et" | "fi" | "fr" | "he" | "hr" | "hu" | "id" | "is" | "it" | "iw" | "ja" | "ko" | "lt" | "lv" | "ms" | "nl" | "no" | "nb" | "nn" | "pl" | "pt" | "pt-BR" | "ro" | "ru" | "sk" | "sl" | "sr" | "sv" | "th" | "tl" | "tr" | "uk" | "vi" | "zh" | "zh-CN" | "zh-TW" | "zh-HK" | "es-MX" | "el" | "bn" | "fil" | "fr-CA" | "hi" | "mr";
            place?: components["schemas"]["PlaceQuery"];
            /**
             * @description Free-text query. Either query or place is required.
             * @example Amsterdam city
             */
            query?: string;
            /**
             * @description Room configuration.
             * @default 2
             */
            rooms: string;
            /** @description The 2-char ISO 3166 country code of a user. */
            userCountry: string;
            /**
             * @description The type of the user's device.
             * @example desktop
             * @enum {string}
             */
            userDevice: "desktop" | "mobile" | "tablet";
            /** @description Return only Vio.com location links. */
            vioOnly?: boolean;
        };
        LocationLinksResponse: {
            /** @description The list of providers links. */
            links?: components["schemas"]["ProviderLink"][];
        };
        NearbyPlace: {
            /**
             * Format: double
             * @description Distance to the place in kilometers.
             */
            distanceKM?: number;
            /**
             * Format: int64
             * @description Number of hotels in the place.
             */
            hotelsCnt?: number;
            /** @description Place category. */
            placeCategory?: string;
            /** @description Place Country. */
            placeCountry?: string;
            /** @description Place ID. */
            placeId?: string;
            /** @description Place name. */
            placeName?: string;
            /** @description The URL that redirects a user to the full search results for this place. */
            url?: string;
        };
        NearbyPlacesRequest: {
            /** @description Unique ID identifying users. Generated automatically when omitted. */
            anonymousId?: string;
            /**
             * Format: date
             * @description Check in date (YYYY-MM-DD).
             * @example 2021-10-10
             */
            checkIn?: string;
            /**
             * Format: date
             * @description Check out date (YYYY-MM-DD).
             * @example 2021-10-11
             */
            checkOut?: string;
            /**
             * @description (Optional) The country name for the main place. If not specified, the first place with the matching name will be used.
             *     It is used to disambiguate between places with the same name in different countries.
             * @example Netherlands
             */
            country?: string;
            /**
             * @description 3-char ISO 4217 currency code.
             * @example EUR
             */
            currency: string;
            /**
             * Format: int64
             * @description Maximum number of results to return. If omitted or non-positive, the default value is 10.
             * @default 10
             * @example 10
             */
            hits: number;
            /** @description Arbitrary string for tracking and reporting. */
            label?: string;
            /**
             * @description Language code that will be used for translation of strings for humans.
             * @example en
             * @enum {string}
             */
            language: "ar" | "bg" | "ca" | "cs" | "cz" | "da" | "de" | "en" | "en-GB" | "es" | "et" | "fi" | "fr" | "he" | "hr" | "hu" | "id" | "is" | "it" | "iw" | "ja" | "ko" | "lt" | "lv" | "ms" | "nl" | "no" | "nb" | "nn" | "pl" | "pt" | "pt-BR" | "ro" | "ru" | "sk" | "sl" | "sr" | "sv" | "th" | "tl" | "tr" | "uk" | "vi" | "zh" | "zh-CN" | "zh-TW" | "zh-HK" | "es-MX" | "el" | "bn" | "fil" | "fr-CA" | "hi" | "mr";
            /**
             * @description Nearby place categories. If not specified, all categories will be used.
             * @example city
             */
            placeCategories?: ("country" | "adminDivision" | "city" | "townVillage" | "subCity" | "landmark" | "touristRegion" | "airport")[];
            /**
             * @description (Optional) The place ID to search for. (placeName will be ignored if both specified)
             * @example 47319
             */
            placeId?: string;
            /**
             * @description The place name to search for. (One of placeName or placeId is required)
             * @example Amsterdam
             */
            placeName?: string;
            /**
             * Format: int64
             * @description Maximum radius in kilometers to search for nearby places. If omitted (or set to 0), the default value is 50 km.
             *     Negative values are rejected.
             * @default 50
             * @example 20
             */
            radius: number;
            /**
             * @description Room configuration.
             * @default 2
             */
            rooms: string;
            /** @description The 2-char ISO 3166 country code of a user. */
            userCountry: string;
            /**
             * @description The type of the user's device.
             * @example desktop
             * @enum {string}
             */
            userDevice: "desktop" | "mobile" | "tablet";
        };
        NearbyPlacesResponse: {
            /** @description List of nearby places. */
            places?: components["schemas"]["NearbyPlace"][];
        };
        Offer: {
            /** @description Offers cancellation penalties. */
            cancellationPenalties: components["schemas"]["CancellationPenalty"][];
            /** @description The currency applied to every rate in the offer. Currency is a 3 letter string following ISO 4217 */
            currency: string;
            metadata?: components["schemas"]["OfferMetadata"];
            package: components["schemas"]["Package"];
            provider: components["schemas"]["Provider"];
            rate: components["schemas"]["Rate"];
            room?: components["schemas"]["Room"];
            /** @description Room name of the offer. */
            roomName: string;
            /** @description The URL that the user should be redirected to book or view more details about this offer. */
            url: string;
        };
        /** @description OfferMetadata contains additional information about the offer */
        OfferMetadata: {
            /** @description Indicates if there is a sign-in deal available for this offer */
            signInDealAvailable?: boolean;
        };
        PAPISuggestResponse: {
            suggestions?: components["schemas"]["Suggestion"][];
        };
        Package: {
            /** @description An array of strings (enums) with the amenities of the offer. */
            amenities: string[];
            /** @description Indicates if the user can be charged later for the offer. */
            canPayLater: boolean;
        };
        Place: {
            /**
             * @description Place address from the requested place to its country.
             * @example London, England, United Kingdom
             */
            address: string;
            /** @description Place ID */
            id: string;
            /** @description Place name. */
            name: string;
            /** @description URL of the place on Vio website. */
            vioUrl: string;
        };
        PlaceQuery: {
            /**
             * @description Country of place. Use this parameter to refine the search
             *     if there are places (e.g. cities) with the same names in another country.
             */
            country?: string;
            /** @description Place name to query. */
            name: string;
        };
        PollSearchResponse: {
            /**
             * Format: int64
             * @description An approximate count of available hotels. For popular places, it's close
             *     to the real number of available hotels. For unpopular places it could be much less.
             *     Available for place searches if "availableHotelsCount" value is specified in the "attributes"
             *     request parameter.
             */
            availableHotelsCount?: number;
            /**
             * @description If true then the polling session is completed
             *     and no more new offers are available.
             *     Keep sending requests to the server until this value is true.
             */
            completed: boolean;
            /** @description The list of hotels that the API failed to map to a Vio.com hotel. */
            failedToMap?: string[];
            /** @description The List of hotels. */
            hotels: components["schemas"]["Hotel"][];
            place?: components["schemas"]["Place"];
            /**
             * @description Unique ID of the polling session.
             *     Put it to the "sessionId" URL query parameter of every subsequent request
             *     in the polling sesson.
             */
            sessionId: string;
            stay?: components["schemas"]["Stay"];
        };
        PriceFilter: {
            /**
             * Format: int64
             * @description Maximum offer price.
             */
            max?: number;
            /**
             * Format: int64
             * @description Minimum offer price.
             */
            min?: number;
        };
        Provider: {
            /** @description Provider icon url. */
            iconUrl?: string;
            /** @description Provider logo url. */
            logoUrl: string;
            /** @description Provider name in english. */
            name: string;
        };
        ProviderLink: {
            /** @description Provider's logo. */
            logo?: string;
            /** @description Provider's name. */
            name?: string;
            /** @description Book url. */
            url?: string;
        };
        Rate: {
            /**
             * Format: double
             * @description The rate exclusive of any taxes and hotel fees.
             */
            base: number;
            /**
             * Format: double
             * @description The sum of all mandatory taxes and fees that the customer will need to pay at the hotel. For example, a resort fee.
             */
            hotelFees: number;
            /**
             * Format: double
             * @description Value added tax (VAT).
             */
            taxes: number;
        };
        Room: {
            /** @description Room amenities in available languages. */
            amenities?: string[];
            /** @description Room images */
            images?: string[];
            layout?: components["schemas"]["Layout"];
            /** @description Room name. */
            name: string;
            /** @description Room type */
            type?: string;
        };
        SearchPageLinkParams: {
            /** @description Arbitrary string for tracking and reporting. */
            label?: string;
            /** @description The list of search page URLs. Each item must be a valid URI. */
            urls?: string[];
        };
        SearchQuery: {
            /** @description The list of hotel IDs to query. */
            hotelIds?: string[];
            /**
             * @description used with the hotelIds query to specify the provider code of
             *     the hotels to query/map.
             */
            hotelIdsProvider?: string;
            hotelNames?: components["schemas"]["HotelNamesQuery"];
            /** @description IATA code of an airport. */
            iataCode?: string;
            /**
             * Format: double
             * @description Latitude in degrees
             */
            lat?: number;
            /**
             * Format: double
             * @description Longitude in degrees
             */
            lon?: number;
            place?: components["schemas"]["PlaceQuery"];
            /** @description Place ID to query. */
            placeId?: string;
            /**
             * @description PrecisionRanges specifies the precision for geographic search results, defined
             *     as a string in "from-value" format, where each pair influences how results are
             *     grouped by distance for ranking purposes.
             *
             *     Each pair in PrecisionRanges is written as "from-value", where `from` is the
             *     starting distance (in meters) and `value` defines the precision for that range.
             *     For example, "0-100" will group all results starting from 0 meters at a precision
             *     of 100 meters, meaning all results within a 0-99 meter radius are ranked equally.
             *
             *     Multiple ranges can be specified as comma-separated pairs, such as
             *     "0-25,1000-2000". In this example, results from 0–999 m have a precision of 25 m,
             *     and results from >= 1000 m are grouped with a precision of 2000 m.
             *
             *     This follows Algolia's aroundPrecision semantics for range objects.
             *
             *     This format allows flexible, non-linear precision grouping to optimize geo-ranking
             *     by reducing overly precise calculations for distant results.
             */
            precision?: string;
            /**
             * Format: int64
             * @description radius in meters
             */
            radius?: number;
        };
        SearchRequest: {
            /** @description Unique ID identifying users. */
            anonymousId?: string;
            /**
             * @description The list of extra attributes to include in a response.
             * @enum {array}
             */
            attributes?: "availableHotelsCount";
            /**
             * Format: date
             * @description Check in date (YYYY-MM-DD). If specified, must be within 0 and 365 days from today.
             * @example 2021-10-10
             */
            checkIn?: string;
            /**
             * Format: date
             * @description Check out date (YYYY-MM-DD). If specified, must be between 1 and 31 days after check-in.
             * @example 2021-10-11
             */
            checkOut?: string;
            /**
             * @description 3-char ISO 4217 currency code.
             * @default EUR
             * @example EUR
             */
            currency: string;
            filters?: components["schemas"]["Filters"];
            /**
             * @description The list of extra hotel attributes to include in a response.
             * @enum {array}
             */
            hotelAttributes?: "details";
            /** @description Arbitrary string for tracking and reporting. */
            label?: string;
            /**
             * @description Language code that will be used for translation of strings for humans.
             * @example en
             * @enum {string}
             */
            language: "ar" | "bg" | "ca" | "cs" | "cz" | "da" | "de" | "en" | "en-GB" | "es" | "et" | "fi" | "fr" | "he" | "hr" | "hu" | "id" | "is" | "it" | "iw" | "ja" | "ko" | "lt" | "lv" | "ms" | "nl" | "no" | "nb" | "nn" | "pl" | "pt" | "pt-BR" | "ro" | "ru" | "sk" | "sl" | "sr" | "sv" | "th" | "tl" | "tr" | "uk" | "vi" | "zh" | "zh-CN" | "zh-TW" | "zh-HK" | "es-MX" | "el" | "bn" | "fil" | "fr-CA" | "hi" | "mr";
            /**
             * @description When enabled, the most cost-effective room combinations will be searched for a given occupancy
             *     (`rooms` field). For example, for 6 people, it will compare offers across different configurations
             *     like one 6-person room ("6"), two 3-person rooms ("3|3"), or three 2-person rooms ("2|2|2"),
             *     returning only the best option per hotel. This feature is not enabled by default, reach the support
             *     if you are going to use it.
             */
            optimizeRooms?: boolean;
            /**
             * Format: int64
             * @description Max number of hotels in a response.
             * @default 20
             */
            pageSize: number;
            query: components["schemas"]["SearchQuery"];
            /**
             * @description Room configuration.
             * @default 2
             */
            rooms: string;
            /**
             * @description Sort criteria.
             * @example price
             * @enum {string}
             */
            sortField?: "price" | "guestRating";
            /**
             * @description Sort order.
             * @default ascending
             * @example ascending
             * @enum {string}
             */
            sortOrder: "ascending" | "descending";
            /**
             * Format: int64
             * @description Maximum time in seconds to process a request. Setting this timeout allows to receive a response without
             *     waiting for offers from slow providers, but it also may lead to an incomplete or empty list of offers in a response.
             */
            timeout?: number;
            /** @description The 2-char ISO 3166 country code of a user. If not specified then API determines it based on the caller's IP address. */
            userCountry: string;
            /**
             * @description The type of the user's device. If not specified then API determines it based on the caller's User-Agent header.
             * @example desktop
             * @enum {string}
             */
            userDevice: "desktop" | "mobile" | "tablet";
        };
        SearchResponse: {
            /**
             * Format: int64
             * @description An approximate count of available hotels. For popular places, it's close
             *     to the real number of available hotels. For unpopular places it could be much less.
             *     Available for place searches if "availableHotelsCount" value is specified in the "attributes"
             *     request parameter.
             */
            availableHotelsCount?: number;
            /** @description The list of hotels that the API failed to map to a Vio.com hotel. */
            failedToMap?: string[];
            /** @description The List of hotels. */
            hotels: components["schemas"]["Hotel"][];
            place?: components["schemas"]["Place"];
            stay?: components["schemas"]["Stay"];
        };
        Stay: {
            /**
             * Format: date
             * @description Check in date (YYYY-MM-DD) which was used in search.
             * @example 2021-10-10
             */
            checkIn?: string;
            /**
             * Format: date
             * @description Check out date (YYYY-MM-DD) which was used in search.
             * @example 2021-10-11
             */
            checkOut?: string;
        };
        Suggestion: {
            /** @description Markup text with occurrences highlighted. */
            highlightValue: string;
            /** @description Object ID. */
            objectID: string;
            /** @description Object ID (legacy casing). */
            objectId: string;
            /**
             * @description Object type.
             * @enum {string}
             */
            objectType: "place" | "hotel" | "nearby";
            /** @description Address display name. */
            placeDisplayName: string;
            /**
             * @description Suggested place type.
             * @enum {string}
             */
            placeTypeName: "property" | "country" | "city" | "airport" | "station" | "area";
            /** @description Full name of the suggestion. */
            value: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        SearchRequest: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    BuildLinks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildLinksRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildLinksResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    List: {
        parameters: {
            query: {
                /** @description Entity of the list. */
                entity: "theme" | "propertyType" | "facility";
                /**
                 * @description Language code to translate values in the list.
                 * @example en
                 */
                language: "ar" | "bg" | "ca" | "cs" | "cz" | "da" | "de" | "en" | "en-GB" | "es" | "et" | "fi" | "fr" | "he" | "hr" | "hu" | "id" | "is" | "it" | "iw" | "ja" | "ko" | "lt" | "lv" | "ms" | "nl" | "no" | "nb" | "nn" | "pl" | "pt" | "pt-BR" | "ro" | "ru" | "sk" | "sl" | "sr" | "sv" | "th" | "tl" | "tr" | "uk" | "vi" | "zh" | "zh-CN" | "zh-TW" | "zh-HK" | "es-MX" | "el" | "bn" | "fil" | "fr-CA" | "hi" | "mr";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListItem"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetLocationLinks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationLinksRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationLinksResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    NearbyPlaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NearbyPlacesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyPlacesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["SearchRequest"];
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    PollSearch: {
        parameters: {
            query?: {
                /** @description The unique identifier of the long-polling session. */
                sessionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["SearchRequest"];
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollSearchResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    Suggest: {
        parameters: {
            query?: {
                /** @description Free text query. */
                query?: string;
                /**
                 * @description Language code of the query.
                 * @example en
                 */
                language?: "ar" | "bg" | "ca" | "cs" | "cz" | "da" | "de" | "en" | "en-GB" | "es" | "et" | "fi" | "fr" | "he" | "hr" | "hu" | "id" | "is" | "it" | "iw" | "ja" | "ko" | "lt" | "lv" | "ms" | "nl" | "no" | "nb" | "nn" | "pl" | "pt" | "pt-BR" | "ro" | "ru" | "sk" | "sl" | "sr" | "sv" | "th" | "tl" | "tr" | "uk" | "vi" | "zh" | "zh-CN" | "zh-TW" | "zh-HK" | "es-MX" | "el" | "bn" | "fil" | "fr-CA" | "hi" | "mr";
                /**
                 * @description Type of suggestions to return. This value is forwarded as an objectType filter.
                 *     Example values include `place`, `hotel`, and `address`. Leave empty for all suggestions.
                 */
                type?: string;
                /** @description Maximum number of suggestions to return. Non-positive values fall back to the default. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PAPISuggestResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
